services:
  db_postgres:
    container_name: db_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user_attendance
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

  
